export const categories = [
  { name: "Uncategorized", color: "#808080", isCustom: false },
  { name: "Aldehydic", color: "#E6E6FA", isCustom: false },
  { name: "Amber", color: "#FFBF00", isCustom: false },
  { name: "Animalic", color: "#A0522D", isCustom: false },
  { name: "Aquatic", color: "#00FFFF", isCustom: false },
  { name: "Aromatic", color: "#9370DB", isCustom: false },
  { name: "Balsamic", color: "#C2B280", isCustom: false },
  { name: "Citrus", color: "#FFA500", isCustom: false },
  { name: "Earthy", color: "#CD853F", isCustom: false },
  { name: "Floral", color: "#FF69B4", isCustom: false },
  { name: "Fruity", color: "#FF6347", isCustom: false },
  { name: "Gourmand", color: "#D2691E", isCustom: false },
  { name: "Green", color: "#008000", isCustom: false },
  { name: "Herbal", color: "#228B22", isCustom: false },
  { name: "Leather", color: "#8B0000", isCustom: false },
  { name: "Mossy", color: "#556B2F", isCustom: false },
  { name: "Musky", color: "#800080", isCustom: false },
  { name: "Ozonic", color: "#87CEFA", isCustom: false },
  { name: "Powdery/Sweet", color: "#FFC0CB", isCustom: false },
  { name: "Resinous", color: "#B8860B", isCustom: false },
  { name: "Spicy", color: "#B22222", isCustom: false },
  { name: "Tobacco/Hay", color: "#D2691E", isCustom: false },
  { name: "Waxy", color: "#C24400", isCustom: false },
  { name: "Woody", color: "#8B4513", isCustom: false },
  { name: "Solvent", color: "#89CFF0", isCustom: false },
];
